import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { NextAuthProvider } from './Providers'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'STLCS',
  description: 'Generated by FAT Groups',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <head>
       <link rel="icon" type="image/x-icon" href="/favicon.ico" /> 
    </head>
      <NextAuthProvider>
        <body>{children}</body>
      </NextAuthProvider>
    </html>
  )
}
